openapi: 3.0.0
info:
  title: Todo App
  description: Todo App api
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server
paths:
  /gettodos:
    get:
      tags:
        - PostTodos
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /posttodos:
    post:
      tags:
        - PostTodos
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  inputText:
                    type: string
                  inputButton:
                    type: boolean
