openapi: 3.0.0
info:
  title: Todo App
  description: Todo App api
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server
paths:
  /gettodos:
    get:
      tags:
        - PostTodos
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /posttodos:
    post:
      tags:
        - Todo
      requestBody:
        description: add todo
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
                active:
                  type: boolean
      responses:
        "200":
          description: ToDo add
  /deletetodo/{id}:
    delete:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      tags:
        - Todos
      responses:
        "200":
          description: cart deleted
  paths:
  /puttodo/{id}:
    put:
      summary: Update a ToDo item
      tags:
        - Todo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: body
          name: todo
          description: Updated todo object
          required: true
          schema:
            type: object
            properties:
              active:
                type: boolean
      responses:
        "200":
          description: ToDo updated successfully
  /dltcomp:
    delete:
      tags:
        - Todos
      responses:
        "200":
          description: cart deleted
